/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelVerif.java
 *
 * Created on 31 oct. 2012, 11:09:48
 */

package com.annot.gui;

import com.annot.room.RefineVanishingPoints;
import com.common.ClippedImage;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;

/**
 *
 * @author vdelaitr
 */
public class PanelVerif extends javax.swing.JFrame {
    static final long serialVersionUID = 0L;

    BufferedImage img;
    MyPanel panel;

    RefineVanishingPoints vp;

    /** Creates new form PanelVerif */
    public PanelVerif(PanelMain main, RefineVanishingPoints vp) {
        this.vp = vp;
        img = vp.alledges;

        initComponents();
        
        setLocation(main.getLocation().x + main.getWidth(), main.getLocation().y);
        setTitle("Check");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        setLayout(new BorderLayout());
       
        panel = new MyPanel(new ClippedImage(img));                
        add(panel, BorderLayout.CENTER);        
        pack();
        //setMinimumSize(new Dimension(getWidth(), getHeight() + 30));

        showImg();
    }

    void showImg() {
        switch (jComboBox1.getSelectedIndex()) {
            case 0:  img = vp.alledges; break;
            case 1:  img = vp.strongEdges; break;
            case 2:  img = vp.alllines; break;
            case 3:  img = vp.mergedLines; break;
            case 4:  img = vp.candidateVPLines; break;
            default: img = vp.vpLines; break;
        }

        panel.setImage(new ClippedImage(img));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Edges", "Strong edges", "Lines", "Merged lines", "Candidate VP lines", "VP lines" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        showImg();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables

}
